{% set name = "bioptim" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/bioptim/archive/Release_{{ version }}.tar.gz
  sha256: 0718ff7cd408a95a012b25b3e4fe2c91b80cbc9c1d0c0faec8b0aeb9c9a1c542

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - matplotlib-base
    - casadi
    - rbdl
    - biorbd
    - bioviz
    - scipy
    - packaging

test:
  imports:
    - bioptim

about:
  home: https://github.com/pyomeca/bioptim
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An optimization framework for Optimal Control Programming in biomechanics
  description: |
    `Bioptim` is an optimal control program (OCP) framework for biomechanics.
    It is based on the efficient `biorbd` biomechanics library and befits from 
    the powerful algorithmic diff provided by CasADi. It interfaces the robust Ipopt
    and fast ACADOS solvers to suit all your needs for an OCP in biomechanics. 
  doc_url: https://github.com/pyomeca/bioptim
  dev_url: https://github.com/pyomeca/bioptim

extra:
  recipe-maintainers:
    - pariterre
