{% set name = "bioptim" %}
{% set version = "3.0.0" %}
{% set build_num = 3 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/{{ name }}/archive/Release_{{ version }}.tar.gz
  sha256: 70205b1f35176f4ea4baa09b988d20ee8351e8c5a4a530bb2414e426a5b77945

build:
  number: {{ build_num }}
  string: py{{ py }}_h{{ PKG_HASH }}_{{ build_num }}
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - biorbd
    - bioviz
    - casadi
    - scipy
    - numpy
    - matplotlib-base
    - packaging

test:
  imports:
    - bioptim

about:
  home: https://github.com/pyomeca/bioptim
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An optimization framework for Optimal Control Programming in biomechanics
  description: |
    `Bioptim` is an optimal control program (OCP) framework for biomechanics.
    It is based on the efficient `biorbd` biomechanics library and befits from 
    the powerful algorithmic diff provided by CasADi. It interfaces the robust Ipopt
    and fast ACADOS solvers to suit all your needs for an OCP in biomechanics. 
  doc_url: https://github.com/pyomeca/bioptim
  dev_url: https://github.com/pyomeca/bioptim

extra:
  recipe-maintainers:
    - pariterre
