{% set name = "bioptim" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/bioptim/archive/Release_{{ version }}.tar.gz
  sha256: 499e7b61f9e64646fb5ef1689ed3e725e3eec6c5b493dc72d15bb615a629eb4d

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - matplotlib-base
    - casadi
    - rbdl =*=*casadi*
    - biorbd =*=*casadi*
    - bioviz =*=*casadi*
    - scipy
    - packaging

test:
  imports:
    - bioptim

about:
  home: https://github.com/pyomeca/bioptim
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An optimization framework for Optimal Control Programming in biomechanics
  description: |
    `Bioptim` is an optimal control program (OCP) framework for biomechanics.
    It is based on the efficient `biorbd` biomechanics library and befits from 
    the powerful algorithmic diff provided by CasADi. It interfaces the robust Ipopt
    and fast ACADOS solvers to suit all your needs for an OCP in biomechanics. 
  doc_url: https://github.com/pyomeca/bioptim
  dev_url: https://github.com/pyomeca/bioptim

extra:
  recipe-maintainers:
    - pariterre
