{% set name = "bioptim" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/bioptim/archive/Release_{{ version }}.tar.gz
  sha256: d5601f9000f29af8cac60a5a0e10b11ebf1252a7efe75e752c482285782a00a4

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - matplotlib-base
    - casadi
    - rbdl
    - biorbd
    - bioviz
    - scipy
    - packaging

test:
  imports:
    - bioptim

about:
  home: https://github.com/pyomeca/bioptim
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An optimization framework for Optimal Control Programming in biomechanics
  description: |
    `Bioptim` is an optimal control program (OCP) framework for biomechanics.
    It is based on the efficient `biorbd` biomechanics library and befits from 
    the powerful algorithmic diff provided by CasADi. It interfaces the robust Ipopt
    and fast ACADOS solvers to suit all your needs for an OCP in biomechanics. 
  doc_url: https://github.com/pyomeca/bioptim
  dev_url: https://github.com/pyomeca/bioptim

extra:
  recipe-maintainers:
    - pariterre
